export const BICYCLES_LOADED = "BICYCLES_LOADED";

export const BICYCLES_SHOULD_BE_RELOADED = 'BICYCLES_SHOULD_BE_RELOADED';

export const IS_BICYCLES_LOADING = 'IS_BICYCLES_LOADING';

export const CREATE_BICYCLE = 'CREATE_BICYCLE';

export const DELETE_BICYCLE = 'DELETE_BICYCLE';